###
GET http://localhost:3050/listeRecette
###
POST http://localhost:3050/ajouterRecette
Content-Type: application/json

{
  "nom": "Patate eee",
  "description": "patate farineuse",
  "etapes": "etape 3",
  "url_etapes": "url.com",
  "id": 3
}
###
GET http://localhost:3050/getRecetteById/19

###
GET http://localhost:3050/getRecetteByNom/pates


###
DELETE http://localhost:3050/supprimerRecette/2

###
PUT http://localhost:3050/modificationIngredient/2
Content-Type: application/json

{
  "nouveauNom": "Nouveau nom",
  "supprimer": true
}

###
GET http://localhost:3050/listeUtilisateur

###
GET http://localhost:3050/listeIngredient



###
PUT http://localhost:3050/modificationIngredient/3
Content-Type: application/json

{
  "nouveauNom": 2.5
}

###
GET http://localhost:3050/getIngredientById/1

###
DELETE http://localhost:3050/supprimerIngredient/2